from .load_random_image import (
    NODE_CLASS_MAPPINGS as LOAD_RANDOM_IMAGE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LOAD_RANDOM_IMAGE_DISPLAY_NAMES,
)
from .random_sublist import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .wildcards_processor import (
    NODE_CLASS_MAPPINGS as WILDCARDS_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as WILDCARDS_DISPLAY_NAMES,
)

NODE_CLASS_MAPPINGS = {
    **NODE_CLASS_MAPPINGS,
    **WILDCARDS_CLASS_MAPPINGS,
    **LOAD_RANDOM_IMAGE_CLASS_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **NODE_DISPLAY_NAME_MAPPINGS,
    **WILDCARDS_DISPLAY_NAMES,
    **LOAD_RANDOM_IMAGE_DISPLAY_NAMES,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
